version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: myappdb
      DB_USER: hamza
      DB_PASSWORD: hamza123
    command: ["./entrypoint.sh"]

  mysql:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myappdb
      MYSQL_USER: hamza
      MYSQL_PASSWORD: hamza123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my-phpmyadmin
    restart: always
    ports:
      - "8080:80"  # accessible sur http://localhost:8080
    environment:
      PMA_HOST: mysql        # doit correspondre au nom du service MySQL
      PMA_USER: hamza
      PMA_PASSWORD: hamza123
    depends_on:
      - mysql

volumes:
  mysql_data:
